apiVersion: v1
kind: List
items:
# Create an ingress gateway deployment that will be the entry point to
# the bookinfo application
- apiVersion: install.tetrate.io/v1alpha1
  kind: IngressGateway
  metadata:
    namespace: bookinfo
    name: tsb-gateway-bookinfo
  spec: {}
# Create the workspace and gateway group that capture the namespaces where
# the bookinfo application will run
- apiVersion: tsb.tetrate.io/v2
  kind: Workspace
  metadata:
    name: bookinfo
    annotations:
      tsb.tetrate.io/organization: demo-webinar0725-org
      tsb.tetrate.io/tenant: demo-webinar0725-tenant  
  spec:
    namespaceSelector:
      names:
        - "*/bookinfo"
- apiVersion: gateway.tsb.tetrate.io/v2
  kind: Group
  metadata:
    name: bookinfo-gg
    annotations:
      tsb.tetrate.io/organization: demo-webinar0725-org
      tsb.tetrate.io/tenant: demo-webinar0725-tenant  
      tsb.tetrate.io/workspace: bookinfo
  spec:
    namespaceSelector:
      names:
        - "*/*"
    configMode: BRIDGED
# Expose the productpage service in the application ingress
- apiVersion: gateway.tsb.tetrate.io/v2
  kind: IngressGateway
  metadata:
    name: bookinfo-gateway
    annotations:
      tsb.tetrate.io/organization: demo-webinar0725-org
      tsb.tetrate.io/tenant: demo-webinar0725-tenant  
      tsb.tetrate.io/workspace: bookinfo
      tsb.tetrate.io/gatewayGroup: bookinfo-gg
  spec:
    workloadSelector:
      namespace: bookinfo
      labels:
        app: tsb-gateway-bookinfo
    http:
      - name: productpage
        port: 80
        hostname: "webinar0725-bookinfo.cx.tetrate.info"
        routing:
          rules:
            - route:
                host: "bookinfo/productpage.bookinfo.svc.cluster.local"
                port: 9080
      - name: details
        port: 9080
        hostname: "details.cx.tetrate.info"
        routing:
          rules:
          - route:
              host: "bookinfo/details.bookinfo.svc.cluster.local"
              port: 9080                   
---
- apiVersion: gateway.tsb.tetrate.io/v2
  kind: Tier1Gateway
  metadata:
    name: bookinfo-tier1
      tsb.tetrate.io/organization: demo-webinar0725-org
      tsb.tetrate.io/tenant: demo-webinar0725-tenant  
      tsb.tetrate.io/workspace: bookinfo
      tsb.tetrate.io/gatewayGroup: bookinfo-gg
  spec:
    workloadSelector:
      namespace: bookinfo-tier1
      labels:
        app: tsb-gateway-bookinfo-tier1
    externalServers:
    - name: bookinfo
      hostname: webinar0725-bookinfo.cx.tetrate.info
      port: 80
      tls: {}              
---